### ISSUE TITLE
main Root Hub port will is not disabled

### ISSUE THREAD

**Issue by itssuryaprasanth** [manavarya999/win-usb-disabler#1]
@manavarya999  Firstly Thanks for creating  this utility to disable main bus driver(Root HUB port). You have done a great job!!

About the issue -->

Windows will not allow to disable the Root USB Hub port,  As it thinks user may alters some things in bios level and it will warn you with below messages.

Failed to disable device:  USB\ROOT_HUB30\4&47e5f5b&0&0
Cannot disable critical system device.

********************************** WARNING **********************************
Interfering with critical system device may adversely impact system operation.
This may affect your ability to boot Windows or access vital hardware resources.

To overcome this, We have to run pnputil in admin mode and for disable command we have add an flag ==> **/f** which force disable the device, after restart it's working.

**Comment by manavarya999** [comment]
@itssuryaprasanth I noticed that only one of the Root USB Hub ports is getting disabled and not all. 

I've added the `/force` argument. Please check and let me know how it goes.

Thank you!

**Comment by itssuryaprasanth** [comment]
Thanks man!
